analysis_task:
  description: >
    Gather details on {company} and its product '{product}'. Research at
    least 3 to 5 competitor products by searching the web to extract their main features,
    pricing models, and recent news or updates. Focus on concise yet comprehensive
    data collection.
  expected_output: >
    A structured overview (2-3 paragraphs) that includes key details
    about {company} and '{product}', along with a high-level summary of competitor
    products highlighting their strengths, weaknesses, and any major differentiators.

insights_task:
  description: >
    Using the research provided from analysis_task, compare '{product}'
    with competitors' products. Deliver a markdown formatted report that includes
    a bullet-point comparison, identifies differentiation points for {company}, and
    provides strategic recommendations and potential improvements.
  expected_output: >
    A final competitive insights report in Markdown format consisting
    of 3-4 paragraphs with bullet points that compare features and market positions,
    and outline strategic recommendations for {company} based on the analysis.